### ISSUE TITLE
Continuesly executing nodes that push out results

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-scijava#36] opened 2016-02-12 22:24 UTC
**Note** This probably requires changes in SciJava core.

A command should be able to push out results (which are properly post-processed) continuously without getting re-executed.
Example use case: 
- A command that reads images from a webcam and pushes them into a processing pipeline.
  - Inputs are static (eg. selected Webcam, processing parameters)
  - Output is updated 30 times a second with the current image from the webcam.

**Comment by dietzc** [comment] 2016-02-13 12:09
another (more simple example): you have one input and n-outputs of the very same type. however, you want to push the n-outputs directly after they have been computed rather than collection them and output them as a list / array or so.

**Comment by gab1one** [comment] 2016-02-16 20:50
## OutputRowSyncService
- Create `OutputRowSyncService`:
  - Commands can call `push(this)` method on it to signal that they want to offload their results to the service.
  - A node can register as a Listener to this service via a `registerListener(RowSyncListener)` method,
    it will get called whenever a result is added to the service.
  - this service harvests the results from the command, (if needed post-processes them)

**Comment by Squareys** [comment] 2016-09-13 09:10
Related to #26

**Comment by dietzc** [comment] 2016-09-22 09:59
Duplicate of #26.

**Closed as completed by dietzc** 2016-09-22 09:59 UTC
